### ISSUE TITLE
Can you pls update Dockerfile with 'bionic'?

### ISSUE THREAD

**Issue by abhyankar-amey** [juanluisbaptiste/xpra-base#2]
Hello Juan,

Just asking if you can update = https://github.com/juanluisbaptiste/xpra-base/blob/master/Dockerfile with 'Bionic'. Xenial is almost end of life I believe. 

Thanks & Regards,
Amey.

**Comment by abhyankar-amey** [comment]
Also will be great if you can update he version of 'docker-compose' to 3  :+1:

**Comment by juanluisbaptiste** [comment]
Hi,

PR welcome.

**Comment by abhyankar-amey** [comment]
@juanluisbaptiste  

1)
Tried to create a pull request [from web browser] but it's giving me message  = Choose different branches or forks above to discuss and review changes. There is no other branch than master :-/ 

2)
If I try to git push from terminal = ameya@Abhyankar:/bitcoin-wallet/docker-bitcoin-wallet$ git push
Username for 'https://github.com': abhyankar-amey
Password for 'https://abhyankar-amey@github.com': 
remote: Permission to juanluisbaptiste/docker-bitcoin-wallet.git denied to abhyankar-amey.
fatal: unable to access 'https://github.com/juanluisbaptiste/docker-bitcoin-wallet/': The requested URL returned error: 403

**Comment by abhyankar-amey** [comment]
@juanluisbaptiste  Done!

I checked entrypoint.sh file.
It is using python 2.7
I compiled with bionic and it's working fine.
I am not a developer so not really sure about impact if we use python 3.
Can you pls have a look? Thanks.

**Comment by juanluisbaptiste** [comment]
I forgot to close this, also I just upgraded to focal.

cheers.
